version: '3.8'  # Use a more recent version for better compatibility
services:
  svmbackend:
    build:
      context: ./App
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app_network

  vggbackend:
    build:
      context: ./VggApp
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8083:8083"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontApp
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - svmbackend
      - vggbackend

networks:
  app_network:
    driver: bridge